### ISSUE TITLE
Chronoline section wrong position

### ISSUE THREAD

**Issue by kviktor** [StoicLoofah/chronoline.js#26]
Code: https://jsfiddle.net/q1ch73p8/
Image:
![image](https://cloud.githubusercontent.com/assets/1112058/10072825/e508cba6-62c4-11e5-8776-c72e3fccb5d5.png)

It should end at jan 30.

**Comment by Padhraic** [comment]
I think this is a error in your `sections` array not Chronoline. 
`new Date` function in javascript used a 0 based month. So Jan = 0, Feb = 1, Mar = 2
See [here](http://www.w3schools.com/js/js_dates.asp) 
Your end date is new Date(2016,1,30) which JavaScript interprets as Mar 1st since there are not 30 days in Feb.

[Here](https://jsfiddle.net/chrustlesstulip/3r0yk3gj/) is an updated jsfiddle with Mar 30th set.

**Comment by StoicLoofah** [comment]
@Padhraic is right (thanks for responding, by the way!). I have been fooled by JavaScript dates many times, but this should address your issue. If there's nothing else, you can close this issue.

Thanks for using chronoline and asking! It's great to hear about people using it.

**Comment by kviktor** [comment]
Thanks for the help, I didn't know JS used 0 based month, it fixed the issue.
